language: java
jdk:
  - openjdk8

branches:
  only:
    - main

before_install:
  - chomod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - 20200803@sungshin.ac.kr